---
swagger: "2.0"
info:
  description: "Keyword Cloud for your current location. A simple API service telling you what's hot near you."
  version: "0.1.0"
  title: "Nearby News"
  termsOfService: "https://github.com/BlueT/nearby-news/blob/master/TOS.txt"
  contact:
    name: "Nearby News team"
    url: "https://github.com/BlueT/nearby-news"
    email: "BlueT@BlueT.org"
  license:
    name: "AGPL-3.0"
    url: "http://opensource.org/licenses/AGPL-3.0"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /users/login:
    post:
      description: "Returns cookie if login success. Check https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject"
      operationId: "user_login"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "login mail"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "login password"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
  /users/logout:
    get:
      description: "user logout"
      operationId: "user_logout"
      produces:
      - "application/json"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
  /users/:
    get:
      description: "回傳使用者列表"
      operationId: "find_users"
      produces:
      - "application/json"
      parameters:
      - name: "school"
        in: "query"
        description: "Latitude of current location"
        required: false
        type: "string"
      responses:
        200:
          description: "find_users response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
  /users/me:
    get:
      description: "Returns self data"
      operationId: "find_user_me"
      produces:
      - "application/json"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
    patch:
      description: "Patch self data"
      operationId: "patch_user_me"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "login mail"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "login password"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
  /users/{id}:
    get:
      description: "Returns a user based on a single ID"
      operationId: "find_user_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of user to fetch"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
    patch:
      description: "Patch user by id"
      operationId: "patch_user_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of user to patch"
        required: true
        type: "integer"
        format: "int64"
      - name: "email"
        in: "formData"
        description: "login mail"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "login password"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
    delete:
      description: "Delete user by id"
      operationId: "delete_user_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of user to de;lete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
  /school/{id}:
    get:
      description: "Returns a school based on a single ID"
      operationId: "find_school_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of school to fetch"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "school response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
    patch:
      description: "Patch school by id"
      operationId: "patch_school_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of school to patch"
        required: true
        type: "integer"
        format: "int64"
      - name: "fullname"
        in: "formData"
        description: "full name"
        required: true
        type: "string"
      - name: "desciption"
        in: "formData"
        description: "introduction"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
    post:
      description: "create new dept under school"
      operationId: "create_dept"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of school to fetch"
        required: true
        type: "integer"
        format: "int64"
      - name: "title"
        in: "formData"
        description: "dept title"
        required: true
        type: "string"
      - name: "desc"
        in: "formData"
        description: "dept intro"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-swagger-router-controller: "Default"
  /school/{id}/{dept_id}:
    patch:
      description: "Patch school by id"
      operationId: "patch_dept_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of school to patch"
        required: true
        type: "integer"
        format: "int64"
      - name: "dept_id"
        in: "path"
        description: "ID of dept to patch"
        required: true
        type: "integer"
        format: "int64"
      - name: "fullname"
        in: "formData"
        description: "full name"
        required: true
        type: "string"
      - name: "desciption"
        in: "formData"
        description: "introduction"
        required: true
        type: "string"
      responses:
        200:
          description: "user response"
          schema:
            $ref: "#/definitions/userModel"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
definitions:
  userModel:
    type: "object"
    required:
    - "email"
    properties:
      id:
        type: "integer"
        format: "int64"
      user_type:
        type: "string" # schools, students, overseas ...
      email:
        type: "string"
      chinese_name:
        type: "string"
      eng_name:
        type: "string"
      password:
        type: "string"
      school_users:
        $ref: "#/definitions/school_users"
      student:
        $ref: "#/definitions/students"
      login_log:
        $ref: "#/definitions/log"
  school_users:
    type: "object"
    required:
    - "school_code"
    properties:
      school_code:
        type: "integer" # 目前學校代碼是 0~FF
      school_name:
        type: "string"
      organization:
        type: "string" # 哪個處室
      office_phone:
        type: "string" # 分機用#分隔
      school_permissions:
        $ref: "#/definitions/school_permissions"
  school_permissions:
    type: "object"
    required:
    - "edit_synopsis"
    properties:
      admin:
        type: "boolean"
      add_users:
        type: "boolean"
      edit_synopsis:
        type: "boolean"
  students: # 嗯先不要管學生
    type: "object"
    required:
    - "source"
    - "source_site"
    - "timestamp"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      location:
        $ref: "#/definitions/location"
      keywords:
        type: "array"
        items:
          type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      source:
        type: "string"
      source_site:
        type: "string"
      category:
        type: "array"
        items:
          type: "string"
      positive:
        type: "boolean"
  log:
    type: "object"
    required:
    - "source"
    - "source_site"
    - "timestamp"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      location:
        $ref: "#/definitions/location"
      keywords:
        type: "array"
        items:
          type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      source:
        type: "string"
      source_site:
        type: "string"
      category:
        type: "array"
        items:
          type: "string"
      positive:
        type: "boolean"
  newsEntry:
    type: "object"
    required:
    - "category"
    - "id"
    - "keywords"
    - "location"
    - "positive"
    - "source"
    - "source_site"
    - "timestamp"
    - "title"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      location:
        $ref: "#/definitions/location"
      keywords:
        type: "array"
        items:
          type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      source:
        type: "string"
      source_site:
        type: "string"
      category:
        type: "array"
        items:
          type: "string"
      positive:
        type: "boolean"
  location:
    type: "object"
    required:
    - "latitude"
    - "longitude"
    properties:
      longitude:
        type: "number"
        format: "float"
      latitude:
        type: "number"
        format: "float"
  keywordEntry:
    type: "object"
    properties:
      keyword:
        type: "number"
        format: "float"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
